config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :birds
  resources :nodes
  get '/common_ancestor', to: 'nodes#common_ancestor'
  get '/nodes_birds', to: 'nodes#nodes_birds'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bird.rb
# frozen_string_literal: true

class Bird < ApplicationRecord
  belongs_to :node
  validates :id, presence: true, uniqueness: true
  validates :node_id, presence: true
end

app/models/node.rb
# frozen_string_literal: true

require 'common_ancestor'
require 'nodes_birds'

class Node < ApplicationRecord
  has_one :parent, class_name: 'Node', primary_key: 'parent_id', foreign_key: 'id'
  has_many :children, class_name: 'Node', foreign_key: 'parent_id'
  has_many :birds
  validates :id, presence: true, uniqueness: true

  def self.common_ancestor(a_id, b_id, method)
    CommonAncestor.find(a_id, b_id, method)
  end

  def self.nodes_birds(node_ids, method)
    NodesBirds.find(node_ids, method)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/birds_controller.rb
# frozen_string_literal: true

class BirdsController < ApplicationController
  before_action :set_bird, only: %i[show edit update destroy]

  # GET /birds or /birds.json
  def index
    @birds = Bird.all
  end

  # GET /birds/1 or /birds/1.json
  def show; end

  # GET /birds/new
  def new
    @bird = Bird.new
  end

  # GET /birds/1/edit
  def edit; end

  # POST /birds or /birds.json
  def create
    @bird = Bird.new(bird_params)

    respond_to do |format|
      if @bird.save
        format.html { redirect_to bird_url(@bird), notice: 'Bird was successfully created.' }
        format.json { render :show, status: :created, location: @bird }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /birds/1 or /birds/1.json
  def update
    respond_to do |format|
      if @bird.update(bird_params)
        format.html { redirect_to bird_url(@bird), notice: 'Bird was successfully updated.' }
        format.json { render :show, status: :ok, location: @bird }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birds/1 or /birds/1.json
  def destroy
    @bird.destroy

    respond_to do |format|
      format.html { redirect_to birds_url, notice: 'Bird was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bird
    @bird = Bird.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bird_params
    params.require(:bird).permit(:id, :node_id)
  end
end

app/controllers/nodes_controller.rb
# frozen_string_literal: true

class NodesController < ApplicationController
  before_action :set_node, only: %i[show edit update destroy]

  # GET /nodes or /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1 or /nodes/1.json
  def show; end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit; end

  # POST /nodes or /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to node_url(@node), notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1 or /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to node_url(@node), notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1 or /nodes/1.json
  def destroy
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def common_ancestor
    render json: Node.common_ancestor(params['a'].to_i, params['b'].to_i, params['method'].to_i)
  end

  def nodes_birds
    if params['node_ids']
      clean_node_ids = params['node_ids'].map(&:to_i).compact
      render json: Node.nodes_birds(clean_node_ids, params['method'])
    else
      render json: { data: {}, meta: {} }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_node
    @node = Node.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def node_params
    params.require(:node).permit(:id, :parent_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/birds_helper.rb
# frozen_string_literal: true

module BirdsHelper
end

app/helpers/nodes_helper.rb
# frozen_string_literal: true

module NodesHelper
end

app/views/birds/_bird.html.erb
<div id="<%= dom_id bird %>">
  <p>
    <strong>Node:</strong>
    <%= bird.node_id %>
  </p>

</div>

app/views/birds/_form.html.erb
<%= form_with(model: bird) do |form| %>
  <% if bird.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bird.errors.count, "error") %> prohibited this bird from being saved:</h2>

      <ul>
        <% bird.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :node_id, style: "display: block" %>
    <%= form.number_field :node_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/birds/edit.html.erb
<h1>Editing bird</h1>

<%= render "form", bird: @bird %>

<br>

<div>
  <%= link_to "Show this bird", @bird %> |
  <%= link_to "Back to birds", birds_path %>
</div>

app/views/birds/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Birds</h1>

<div id="birds">
  <% @birds.each do |bird| %>
    <%= render bird %>
    <p>
      <%= link_to "Show this bird", bird %>
    </p>
  <% end %>
</div>

<%= link_to "New bird", new_bird_path %>

app/views/birds/new.html.erb
<h1>New bird</h1>

<%= render "form", bird: @bird %>

<br>

<div>
  <%= link_to "Back to birds", birds_path %>
</div>

app/views/birds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bird %>

<div>
  <%= link_to "Edit this bird", edit_bird_path(@bird) %> |
  <%= link_to "Back to birds", birds_path %>

  <%= button_to "Destroy this bird", @bird, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NodeProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nodes/_form.html.erb
<%= form_with(model: node) do |form| %>
  <% if node.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
        <% node.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :parent_id, style: "display: block" %>
    <%= form.number_field :parent_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/nodes/_node.html.erb
<div id="<%= dom_id node %>">
  <p>
    <strong>Parent:</strong>
    <%= node.parent_id %>
  </p>

</div>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render "form", node: @node %>

<br>

<div>
  <%= link_to "Show this node", @node %> |
  <%= link_to "Back to nodes", nodes_path %>
</div>

app/views/nodes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Nodes</h1>

<div id="nodes">
  <% @nodes.each do |node| %>
    <%= render node %>
    <p>
      <%= link_to "Show this node", node %>
    </p>
  <% end %>
</div>

<%= link_to "New node", new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render "form", node: @node %>

<br>

<div>
  <%= link_to "Back to nodes", nodes_path %>
</div>

app/views/nodes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @node %>

<div>
  <%= link_to "Edit this node", edit_node_path(@node) %> |
  <%= link_to "Back to nodes", nodes_path %>

  <%= button_to "Destroy this node", @node, method: :delete %>
</div>